# Generated by Django 3.2 on 2021-05-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={},
        ),
        migrations.RemoveField(
            model_name='specification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='specification',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specification',
            name='coloration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specification',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='nesting',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specification',
            name='occurrence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specification',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.specification'),
        ),
    ]
