# Generated by Django 3.2 on 2021-05-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formicary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('rating', models.FloatField(default=1.0)),
                ('availability', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('formicary_material', models.CharField(max_length=100)),
                ('additional_info', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('rating', models.FloatField(default=1.0)),
                ('availability', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=100)),
                ('coloration', models.CharField(max_length=100)),
                ('occurrence', models.CharField(max_length=255)),
                ('nesting', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
    ]
