# Generated by Django 3.2 on 2021-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210520_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
