# Generated by Django 3.2 on 2021-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210510_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formicary',
            options={'ordering': ['title'], 'verbose_name_plural': 'Formicaries'},
        ),
        migrations.AddField(
            model_name='formicary',
            name='size',
            field=models.CharField(default='22cm', max_length=100),
            preserve_default=False,
        ),
    ]
