# Generated by Django 2.2.17 on 2021-05-28 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210527_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New order'), ('in_progress', 'Order in prgress'), ('is_ready', 'Order is ready'), ('completed', 'Order completed')], default='new', max_length=100)),
                ('buying_type', models.CharField(choices=[('self', 'Self-pickup'), ('delivery', 'Delivery')], default='self', max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
