# Generated by Django 3.2 on 2021-05-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210514_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='card',
            new_name='cart',
        ),
    ]
